spring:
    profiles: development
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/mdh?useUnicode=true&haracterEncoding=UTF&useSSL=false&serverTimezone=UTC
        username: root
        password: 1220
    thymeleaf:
        mode: HTML
        prefix: classpath:/templates/
        suffix: .html
        cache: false
mybatis:
    mapper-locations: classpath:mapper/**/*.xml
    config-location: classpath:mybatisConfig.xml
---
spring:
    profiles: production